### ISSUE TITLE
Don't call it a template.

### ISSUE THREAD

**Issue by nothingismagick** [kpapro/quasar-firebase-firestore#2]
@adamkpurdy - this is not a template, it is an example.

**Comment by adamkpurdy** [comment]
I'll take it into consideration, but I'm not sure if this is really worthy of an issue as I feel this is a matter of opinion that could have been discussed in the quasar discord chat considering we're both staff members, and our professional relationship.

**Comment by adamkpurdy** [comment]
Changed it to "An opinionated example". ;-)
