### ISSUE TITLE
Consider using async boot functions

### ISSUE THREAD

**Issue by nothingismagick** [kpapro/quasar-firebase-firestore#4]
Not sure if you knew this, but async is available and might be the way to go for some of your boot files.

**Comment by adamkpurdy** [comment]
I went down this route with the auth functions in the firebase boot file, but I didn't like how the functions were resolving for this particular use case. As far as top level async files, I didn't see a need for them. If you have specifics can you please elaborate and resubmit an issue with an example. Thanks.
